name: "Invoke Terraform with Auto Apply"
description: "Invoke Terraform with Auto Apply"
env:
      GENESYSCLOUD_OAUTHCLIENT_ID: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID }}
      GENESYSCLOUD_OAUTHCLIENT_SECRET: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET }}
      TF_VAR_GENESYSCLOUD_OAUTHCLIENT_ID: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID }}
      TF_VAR_GENESYSCLOUD_OAUTHCLIENT_SECRET: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET }}
      TF_VAR_GENESYSCLOUD_REGION: ${{ secrets.GENESYSCLOUD_REGION}}
runs:
  using: "composite"
  steps:
    - run: |
        cd $GITHUB_WORKSPACE/Flow_TF/
        terraform init 
        terraform apply --auto-approve
        cd $GITHUB_WORKSPACE
      shell: bash