name: "Invoke Terraform with Auto Apply"
description: "Invoke Terraform with Auto Apply"
runs:
  using: "composite"
  steps:
    - run: |
        cd $GITHUB_WORKSPACE/Dev/
        terraform init
        terraform state push sv-Sn7BEL57doEwqeAc.tfstate
        terraform apply --auto-approve
        cd $GITHUB_WORKSPACE
      shell: bash