name: Genesys Cloud Deploy Flow
on:
  push:
  branches: [main]
  workflow_dispatch:
  jobs:
deploy-flow:
 runs-on: ubuntu-latest
 env:
   GENESYSCLOUD_OAUTHCLIENT_ID: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_ID }}
   GENESYSCLOUD_OAUTHCLIENT_SECRET: ${{ secrets.GENESYSCLOUD_OAUTHCLIENT_SECRET }}
   GENESYSCLOUD_REGION: ${{ SECRETS.GENESYSCLOUD_REGION }}
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - uses: ./.github/actions/genesys-cloud-apply-terraform